diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
safe.directory=E:/UTC-BG/cipher_api
safe.directory=E:/UTC-BG/cipher_ui
safe.directory=E:/UTC-BG/SmartContracts
safe.directory=E:/UTC-BG/cipher_ui_backoffice/cipher_ui
safe.directory=E:/UTC-BG/bg_smc
safe.directory=E:/UTC-BG/cipher_ui_verification
safe.directory=E:/MyWork/go-micro
safe.directory=E:/UTC-BG/bo/cipher_ui
user.name=TuahaAjaz
user.email=tuahaajaz2000@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/TuahaAjaz/go-micro.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
